name: Build Package

on:
  workflow_dispatch:
    inputs:
      version:
        # Which version (tag in centos kernel repo) to build. Defaults to latest c8
        description: 'Version'
        default: c8
        required: false

jobs:
  build-package:
    runs-on: ubuntu-latest
    container: 
      image: japz/build-bcache-kernel
      env:
        COPR_TOKEN: ${{secrets.COPR_TOKEN}}
        VERSION: ${{ inputs.version }}
