name: Build Package

on:
  workflow_dispatch:
    inputs:
      version:
        # Which version (tag in centos kernel repo) to build. Defaults to latest c8
        description: 'Version'
        default: c8
        required: false

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pull Docker image
      run: docker pull "docker.pkg.github.com/$GITHUB_REPOSITORY/build-bcache-kernel:latest"

    - name: Set COPR token
      run: echo "$COPR_TOKEN" > copr-token
      env:
        COPR_TOKEN: ${{secrets.COPR_TOKEN}}

    - name: Run image
      run: docker run -it --name builder -v $GITHUB_WORKSPACE:/workspace -v copr-token:/rpmbuild/.config/copr -w /workspace docker.pkg.github.com/$GITHUB_REPOSITORY/build-bcache-kernel:latest

