on:
  repository_dispatch:
    types: build-package

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
    - name: Build package	    
      uses: docker://${{ github.repository }}:latest
      env:
        COPR_TOKEN: ${{secrets.COPR_TOKEN}}
